# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beats, Bakes, & Bytes.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Aspiring software engineer. Baking enthusiast, DJ, and writer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kimerie.github.io" # the base hostname & protocol for your site
twitter_username: Kimerieg
github_username:  kimerie

# Build settings
markdown: kramdown
